title: John Doe
author: John Doe
email: your-email@domain.com
logo: /assets/img/logo.png
description:
  I am a -----
    <br>
    <br>
  Short Description of my experience
  <br>
  <br>
  <p class="view">
    <a href="{{ site.linkedin }}">
      View My LinkedIn Profile
    </a>
  </p>
  <p class="view">
    <a href="{{ site.github-url }}">
      View My GitHub Profile
    </a>
  </p>

show_downloads: false

google_analytics:
theme: jekyll-theme-minimal-elcymon
show_excerpts: true